name: Download and Extract Wine Apk

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        run: |
          wget -O install.apk "https://github.com/brunodev85/winlator/releases/download/v11.1.0/Winlator_11.1.apk"

      - name: Extract APK
        run: |
          mkdir install_apk
          unzip install.apk -d install_apk

      - name: Search ABI folders
        run: |
          echo "Searching armeabi-v7a:"
          find install_apk -iname "*armeabi-v7a*" -print

          echo ""
          echo "Searching arm64:"
          find install_apk -iname "*arm64*" -print

      - name: Check windows-arm support
        run: |
          find install_apk -iname "*arm*"

      - name: Check windows-x86 support
        run: |
          find install_apk -iname "*x86*"