name: Download and Extract Apk

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        run: |
          wget -O install.apk "https://github.com/brunodev85/winlator/releases/download/v7.1.0/Winlator_7.1.apk"

      - name: Extract APK
        run: |
          mkdir install_apk
          unzip install.apk -d install_apk

      - name: List 64 of apk
        run: |
          echo "=====Folders:"
          find install_apk -type d -iname "*64*" | sort
          echo
          echo"=====Files:"
          find install_apk -type f -iname "*64*" | sort

      - name: Extract imagefs.txz
        run: |
          mkdir -p imagefs
          tar -xf install_apk/assets/imagefs.txz -C imagefs

      - name: List 64 of imagefs
        run: |
          echo "===== Directories containing '64' ====="
          find imagefs -type d -iname "*64*" | sort

          echo
          echo "===== Files containing '64' ====="
          find imagefs -type f -iname "*64*" | sort  

      - name: Delete 64 bit folders
        run: |
          echo "Removing 64-bit directories..."

          rm -rf imagefs/usr/lib/aarch64-linux-gnu
          rm -rf imagefs/usr/lib/x86_64-linux-gnu
          rm -rf imagefs/opt/wine/lib/wine/x86_64-unix
          rm -rf imagefs/opt/wine/lib/wine/x86_64-windows

          echo "Remaining files containing '64':"
          find imagefs -type f -iname "*64*" | sort || true